"""Weak-supervision and biological objectives for HEIR."""

from .biological import (
    anchor_classification_loss,
    anchor_loss,
    boundary_graph_loss,
    cycle_consistency_loss,
    cycle_loss,
    graph_boundary_loss,
    hierarchy_consistency_loss,
    hierarchy_loss,
    mahalanobis_residual_loss,
    marker_centroid_loss,
    marker_loss,
    marker_ranking_loss,
    program_loss,
    program_score_loss,
    pseudobulk_loss,
    residual_gaussian_kl_loss,
    residual_mahalanobis_loss,
    scgpt_representation_loss,
    type_conditioned_program_score_loss,
    unknown_calibration_loss,
)
from .composite import CompositeLoss, HEIRCompositeLoss, HEIRLossConfig, LossConfig
from .distribution import (
    UnbalancedSinkhornResult,
    aggregate_composition,
    composition_bounds_loss,
    composition_js_loss,
    dirichlet_composition_prior_loss,
    dirichlet_prior_loss,
    jensen_shannon_composition_loss,
    prototype_uot,
    soft_composition_bounds_loss,
    unbalanced_sinkhorn,
    unbalanced_sinkhorn_loss,
)

__all__ = [
    "anchor_classification_loss",
    "anchor_loss",
    "boundary_graph_loss",
    "cycle_consistency_loss",
    "cycle_loss",
    "graph_boundary_loss",
    "hierarchy_consistency_loss",
    "hierarchy_loss",
    "mahalanobis_residual_loss",
    "marker_centroid_loss",
    "marker_ranking_loss",
    "marker_loss",
    "program_loss",
    "program_score_loss",
    "type_conditioned_program_score_loss",
    "pseudobulk_loss",
    "residual_gaussian_kl_loss",
    "residual_mahalanobis_loss",
    "scgpt_representation_loss",
    "unknown_calibration_loss",
    "CompositeLoss",
    "HEIRCompositeLoss",
    "HEIRLossConfig",
    "LossConfig",
    "UnbalancedSinkhornResult",
    "aggregate_composition",
    "composition_bounds_loss",
    "composition_js_loss",
    "dirichlet_composition_prior_loss",
    "dirichlet_prior_loss",
    "jensen_shannon_composition_loss",
    "prototype_uot",
    "soft_composition_bounds_loss",
    "unbalanced_sinkhorn",
    "unbalanced_sinkhorn_loss",
]
